version: "3"
networks:
  default:
    external:
      name: ${BUILD_NET}

volumes:
  dbdata:

services:
  ui:
    container_name: smart-table-ui
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - $PWD:/app:cached
    working_dir: /app
    command: sh -c "npm run start"
    ports:
      - 3000:3000
    networks:
      - default
