version: "3"
networks:
  default:
    external:
      name: ${BUILD_NET}

volumes:
  dbdata:

services:
  ui:
    container_name: smart-table-ui
    image: node:12.10.0
    volumes:
      - $PWD:/app:cached
    working_dir: /app
    command: sh -c "npm i && npm run start"
    ports:
      - 3000:3000
    networks:
      - default
