version: "3"
networks:
  default:
    external:
      name: ${BUILD_NET}

volumes:
  dbdata:

services:
  server:
    container_name: smart-table-server
    build:
      context: server
      dockerfile: ./build/node/Dockerfile
    command: sh -c "npm run migrate:up && node dist/bin/init-data.js && node dist/bin/api.js"
    env_file: ./server/build/.env.list
    depends_on:
      - db
    networks:
      - default

  client:
    container_name: smart-table-client
    build:
      context: client
      dockerfile: ./Dockerfile
    networks:
      - default

  proxy:
    container_name: smart-table-proxy
    build:
      context: proxy
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - default

  db:
    container_name: smart-table-db
    image: postgres:9.6.11-alpine
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file: ./server/build/.env.list
    logging:
      driver: none
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smart-design
    networks:
      - default
