version: "3"
networks:
  default:
    external:
      name: ${BUILD_NET}

volumes:
  dbdata:

services:
  server:
    container_name: smart-table-server
    build:
      context: server
      dockerfile: ./build/node/Dockerfile.prod
    volumes:
      - $PWD/server:/app:cached
    working_dir: /app
    env_file: ./server/build/.env.list
    command: sh -c "node ./dist/bin/api.js"
    depends_on:
      - db
    networks:
      - default

  client:
    container_name: smart-table-client
    build:
      context: client
      dockerfile: ./Dockerfile.prod
    volumes:
      - $PWD/client:/app:cached
    working_dir: /app
    networks:
      - default

  proxy:
    container_name: smart-table-proxy
    build:
      context: proxy
      dockerfile: ./Dockerfile
    volumes:
      - $PWD/proxy:/app:cached
    working_dir: /app
    ports:
      - 80:80
    networks:
      - default

  db:
    container_name: smart-table-db
    image: postgres:9.6.11-alpine
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file: ./server/build/.env.list
    logging:
      driver: none
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smart-design
    networks:
      - default
