version: "3"
networks:
  default:
    external:
      name: ${BUILD_NET}

volumes:
  dbdata:

services:
  api:
    container_name: smart-table-api
    build:
      context: .
      dockerfile: build/node/Dockerfile
    image: smart-table:latest
    volumes:
      - $PWD:/app:cached
    working_dir: /app
    env_file: ./build/.env.list
    command: sh -c "npm run api:start"
    ports:
      - 5000:5000
    depends_on:
      - postgresql
    networks:
      - default

  postgresql:
    container_name: smart-table-postgresql
    image: postgres:9.6.11-alpine
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file: ./build/.env.list
    restart: "no"
    logging:
      driver: none
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smart-design
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    logging:
      driver: none
    ports:
      - 8080:8080
    networks:
      - default
