version: "3"
networks:
  smart-design:
    external: true

volumes:
  dbdata:

services:
  api:
    container_name: smart-table-api
    build:
      context: .
      dockerfile: build/node/Dockerfile
    image: smart-table:latest
    volumes:
      - $PWD:/app:cached
    working_dir: /app
    command: sh -c "npm run api:start"
    networks:
      - smart-design
    ports:
      - 5000:5000
    depends_on:
      - postgresql

  postgresql:
    container_name: smart-table-postgresql
    image: postgres:9.6.11-alpine
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file: ./build/.env.list
    restart: "no"
    logging:
      driver: none
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smart-design
