FORMAT: 1A

# Smart Table

Генерация документации по схеме:

`$ cd /public/schema`

`$ docker run -it --rm -v $PWD:/doc quay.io/bukalapak/snowboard:v3.6.0 html --watch --watch-interval 100ms -o index.html -c config.yaml api.apib`


# Group system
Системные методы

## Schema [/schema/api.apib]

### Get schema [GET]
Получить схему api в формате BluePrint

+ Request json (application/json)

    + Headers

            Authorization: test

+ Response 200
    + Attributes (object)

# Group Users
Методы для получения пользователей

## Users [/api/users]

### Get users [GET]
Получить пользователей

+ Request (application/json)

    + Headers

            Authorization: test

+ Response 200 (application/json)
    + Body

            {
                results: [
                    {
                        id: '1',
                        username: 'Nick'
                    }
                ]
            }

# Group Bugs
Методы для получения багов

## Bugs [/api/bugs{?page,pageSize,userId,searchBy}]

### Get bugs [GET]
Получить баги

+ Request (application/json)

    + Headers

            Authorization: test

+ Parameters

    + page (number, optional)

        Page number

    + pageSize (number, optional)

        Page size

    + userId (number, optional)

        User id

    + searchBy (string, optional)

        Search

+ Response 200 (application/json)
    + Body

            {
                links: {
                    next: 'http://localhost:5000/api/bugs?page=2&pageSize=20'
                },
                results: [
                    {
                        id: '1',
                        title: 'Title',
                        assignee: 'Nick'
                    }
                ],
                page: 1,
                pageSize: 20
            }
